services:
  backend:
    build: 
      context: ./novametrics-backend
      dockerfile: Dockerfile
    container_name: novametrics-backend
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - MQTT_BROKER=broker.hivemq.com
      - MQTT_PORT=1883
      - MQTT_TOPIC=novametrics/projekti/2026/testi
      - PYTHONUNBUFFERED=1
    restart: always